### ISSUE TITLE
Not found: 404 error

### ISSUE THREAD

**Issue by mssmison** [NimmLor/esp8266-fastled-iot-webserver#12]
Is there a specific version of websockets that should be used? Everything compiles and uploads properly but after connecting to the AP I only get : Not found: /

**Comment by NimmLor** [comment]
The website shows the "Not found :/" message because you haven't uploaded the Sketch-Date correctly. You will have to install the Sketch-Data-Uploader beforehand, afterwards upload the data (tools >> ESP8266 Sketch Data Upload).

Install it as shown in the installation setup guide:
https://youtu.be/d-uNkFHoMHc?t=195

**Comment by mssmison** [comment]
Firstly, thank you for the speedy reply. Secondly my apologies for not reading the documentation clearly enough. 
Cheers
