### ISSUE TITLE
Sleep Mode if LED powered off

### ISSUE THREAD

**Issue by thommycgn** [NimmLor/esp8266-fastled-iot-webserver#199]
The Desk Lamp still consumes 1 W when switched off. I noticed that no sleep mode of the ESP is used at all. Is there a reason for this? Could this perhaps still be implemented?

**Comment by WarDrake** [comment]
The ESP and leds all continue to draw power while connected, that's because there are multiple thigns running like a webserver, math calculations, mqtt / alexa alive packages, etc, etc, etc

you could implement a virtual switch like a mosfet to cut the power to the leds and avoid 99% of the power draw, there's a PR for that already made, but no one has had the time to test it, you can try that one if you're interested.

**Comment by hexenmeister** [comment]
see here:
https://github.com/NimmLor/esp8266-fastled-iot-webserver/pull/169
I've been using it myself for some time without any problems :)
![Schematic](https://user-images.githubusercontent.com/2823400/130507160-46f90c86-151c-4f69-ab28-e5f36580f342.jpg)
![gerbers png_Combined_Top](https://user-images.githubusercontent.com/2823400/130507226-d09eae64-0e5a-4bc9-b0dd-7cd3e8706d88.png)
![gerbers png_Combined_Bottom](https://user-images.githubusercontent.com/2823400/130507228-7ddeab4d-6eb5-4fa2-aca8-e80f28767c8a.png)
